###
//Obtener todos los Admin
GET http://localhost:3000/api/admin HTTP/1.1

###
//Crear Admin
POST http://localhost:3000/api/admin HTTP/1.1
Content-Type: application/json

{
    "nombre":"Diego Rojas",
    "documento": 1033703977 ,
    "correo": "diegorojer@gmail.com",
    "telefono": 3007034174,
    "contrasena": "123"
}

###
//Conseguir un unico admin
GET http://localhost:3000/api/admin/1033703977 HTTP/1.1

###
//Actualizar admin
PUT http://localhost:3000/api/admin/1033703977 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Diego Rojas Panteve"
}

###
// Eliminar admin
DELETE http://localhost:3000/api/admin/1033703977 HTTP/1.1
