//Obtener todos los pedidos
GET http://localhost:3000/api/pedido HTTP/1.1

###
//Agregar pedido
POST http://localhost:3000/api/pedido HTTP/1.1
Content-Type: application/json

{
    "documentoDueño": 55200385,
    "productos": [{
        "producto": "NK109",
        "cantidad": 2
    }]
}

###
//Conseguir un unico pedido
GET http://localhost:3000/api/pedido/0001 HTTP/1.1

###
// Eliminar pedido
DELETE http://localhost:3000/api/pedido/0008 HTTP/1.1