//Obtener todos los productos
GET http://localhost:3000/api/producto HTTP/1.1

###
//Crear productos 
POST http://localhost:3000/api/producto HTTP/1.1
Content-Type: application/json

{
    "refproducto": "NK109" ,
    "nombre": "Air Jordan 1 Low" ,
    "precio": 350000 ,
    "descripcion": "¡Rosa para ganar! Tu calzado favorito aparece en una combinación de colores clásica: rosa cálido y negro. Todas las características clásicas del AJ1 también están ahí: Nike Air en la suela para brindar un paso amortiguado y esa suela cupsole de goma que te garantiza comodidad todos los días." ,
    "imagen": ["https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/9ac7ac28-7e8f-4c3d-bd66-4c03462f3283/calzado-grandes-air-jordan-1-low-gpHZPt.png" ,"https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/f620097d-6639-44c1-9808-3b4c576c4299/calzado-grandes-air-jordan-1-low-gpHZPt.png","https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/381fe6a1-2422-44b8-8511-6b122be26c01/calzado-grandes-air-jordan-1-low-gpHZPt.png"],
    "stock": 15,
    "proveedor": "Nike"
}

###
//Conseguir un unico producto
GET http://localhost:3000/api/producto/6605d95c760b4bac4e6a791b HTTP/1.1

###
//Actualizar admin
PUT http://localhost:3000/api/producto/NK109 HTTP/1.1
Content-Type: application/json

{
    
}


###
DELETE http://localhost:3000/api/producto/NK109 HTTP/1.1